global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'ai-pipeline'
  routes:
    - receiver: 'null'
      matchers:
        - alertname = "Watchdog"
    - receiver: 'null'
      matchers:
        - alertname = "KubeControllerManagerDown"
    - receiver: 'null'
      matchers:
        - alertname = "KubeSchedulerDown"
    - receiver: 'null'
      matchers:
        - alertname = "KubeletTooManyPods"
    - receiver: 'null'
      matchers:
        - alertname = "KubeSchedulerDown"
    - receiver: 'ai-pipeline'
      matchers:
        - alertname = "PodCrashLooping"
    - receiver: 'ai-pipeline'
      matchers:
        - alertname = "HighCPUUsage"
    - receiver: 'ai-pipeline'
      matchers:
        - alertname = "HighMemoryUsage"
    - receiver: 'ai-pipeline'
      matchers:
        - alertname = "NodeNotReady"
receivers:
  - name: 'null'
  - name: 'ai-pipeline'
    webhook_configs:
      - url: 'https://e6kol6kfdwutji3zquq5kl7eji0iwwhx.lambda-url.eu-west-2.on.aws/'
        send_resolved: false
inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['alertname', 'namespace']